apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::263553693537:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1TLS427H3TDB5
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::263553693537:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-13T18:18:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1696"
  uid: 760f5701-26a6-477a-be04-0702ce74b091
